from typing import Dict

class PyPGConnectionParameters:
    """
    Stub for PyPGConnectionParameters.

    Connection parameters for PostgreSQL database.
    Provides both connection URL and dictionary formats.

    Optimized with __slots__ for reduced memory footprint.
    """
    __slots__ = ["_url", "_dict"]

    def __init__(self, host: str, port: int, user: str, password: str, database: str) -> None: ...
    def to_dict(self) -> Dict[str, str | int]: ...
    def to_url(self) -> str: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class CyPGConnectionParameters:
    """
    Stub for CyPGConnectionParameters.

    Cython cdef class for PostgreSQL connection parameters.
    """
    def __init__(self, host: str, port: int, user: str, password: str, database: str) -> None: ...
    def to_dict(self) -> dict: ...
    def to_url(self) -> str: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    @property
    def url(self) -> str: ...
